FROM --platform=linux/amd64 ruby:3.2.3-alpine

# Installation path
ENV HOME=/app
WORKDIR $HOME

RUN set -ex && \
  adduser -h $HOME -s /bin/false -D -S -G root ruby && \
  chmod g+w $HOME && \
  apk add --update --no-cache make gcc libc-dev

RUN gem install bundler -v "~> 2.4"
COPY packaging/Gemfile packaging/Gemfile.lock $HOME/
RUN bundle install --no-cache
