#!/bin/bash

IMAGE=pact-standalone-bundle-base
RELEASE_IMAGE=pact-standalone-release-base
PACKAGE_IMAGE=pact-standalone-package-base

function docker-build-bundle-base() {
  docker build . -f Dockerfile-bundle-base -t ${IMAGE}
}

function docker-build-release-base() {
  docker build . -f Dockerfile-release-base -t ${RELEASE_IMAGE}
}

function docker-build-package-base() {
  docker build . -f Dockerfile-package-base -t ${PACKAGE_IMAGE}
}

function on-docker() {
  docker run --platform=linux/amd64 --rm -v ${PWD}:/app $IMAGE:latest sh -c "$@"
}

function on-release-docker() {
  docker run --platform=linux/amd64 --rm -v ${PWD}:/app $RELEASE_IMAGE:latest sh -c "$@"
}

function bundle-update() {
  rm -rf tmp
  docker run --platform=linux/amd64 --rm -v ${PWD}/tmp:/tmp/gemfile ${IMAGE}:latest sh -c "bundle update && cp Gemfile.lock /tmp/gemfile"
  mv tmp/Gemfile.lock packaging/
}
function pkg_copy() {
  rm -rf tmp pkg
  docker run --platform=linux/amd64 --rm -v ${PWD}/tmp:/tmp/pkg ${PACKAGE_IMAGE}:latest sh -c "bundle exec rake package && cp -r pkg /tmp/pkg"
  mv tmp/pkg pkg/
}

function bump-version() {
  on-release-docker "bundle exec bump ${1:-minor} --no-commit"
}

function generate-changelog() {
  on-release-docker "bundle exec rake generate_changelog"
}
