#!/usr/bin/env bash

IMAGE=pact-ruby-standalone-bundle-base

function docker-build-bundle-base() {
  docker build . -f Dockerfile-bundle-base -t ${IMAGE}
}

function on-docker() {
  docker run --rm -v ${PWD}:/app $IMAGE:latest sh -c "$@"
}

function bundle-update() {
  rm -rf tmp
  docker run --rm -v ${PWD}/tmp:/tmp/gemfile ${IMAGE}:latest sh -c "bundle update && cp Gemfile.lock /tmp/gemfile"
  mv tmp/Gemfile.lock packaging/
}

function bump-version() {
  on-docker "bundle exec bump ${1:-minor} --no-commit"
}

function generate-changelog() {
  on-docker "bundle exec rake generate_changelog"
}
