source 'http://rubygems.org'

gem "pact", "1.62.0"
gem "pact-message", "0.11.1"
gem "pact-mock_service", "3.9.0"
gem "pact-provider-verifier", "1.36.1"
gem "pact_broker-client", "1.65.0"
gem "webrick", "1.3.1" # Later versions require Ruby 2.3
gem "rack", "~>2.1.4"
gem "json", "2.0.4"
