source 'http://rubygems.org'

gem "pact", "1.63.0"
gem "pact-message", "0.11.1"
gem "pact-mock_service", "3.11.0"
gem "pact-provider-verifier", "1.36.1"
gem "pact_broker-client", "1.66.1"
gem "webrick", "1.8.1"
gem 'rack', '>= 2.2.6'
gem "json", "2.6.3"
gem 'rack-test', '~> 2.1'
# Locking this until we have given rack-test 3.0 a good shake out in pure Ruby
# gem "rack-test", ">= 0.6.3", "< 2.0.0"