source 'http://rubygems.org'

gem "pact", "1.65.1"
gem "pact-message", "0.11.1"
gem "pact-mock_service", "3.11.2"
gem "pact-provider-verifier", "1.38.1"
gem "pact_broker-client", "1.76.1"
gem "webrick", "1.8.1"
gem 'rack', '>= 2.2.6'
# see https://stdgems.org/ for versions to lock to
# we require gem locking for gems with native extensions
# due to lack of windows support
gem "json", "2.7.1"
gem "bigdecimal", "3.1.5"